# Pytorch tutorial


![](https://miro.medium.com/max/1000/0*1HWz9KQ-duZZykT7.png)


reference : https://pytorch.org/docs/master/torch.html
https://datascienceschool.net/view-notebook/4f3606fd839f4320a4120a56eec1e228/

In [1]:
_ inplace true 

SyntaxError: invalid syntax (<ipython-input-1-60edeab97733>, line 1)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Create-Tensor" data-toc-modified-id="Create-Tensor-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Create Tensor</a></span><ul class="toc-item"><li><span><a href="#Zeros,-ones,-arrange" data-toc-modified-id="Zeros,-ones,-arrange-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Zeros, ones, arrange</a></span></li></ul></li><li><span><a href="#TORCH.TENSOR" data-toc-modified-id="TORCH.TENSOR-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>TORCH.TENSOR</a></span></li><li><span><a href="#Numpy-to-Tensor-&amp;-Tensor-toNumpy" data-toc-modified-id="Numpy-to-Tensor-&amp;-Tensor-toNumpy-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Numpy to Tensor &amp; Tensor toNumpy</a></span><ul class="toc-item"><li><span><a href="#Numpy--->-Tensor" data-toc-modified-id="Numpy--->-Tensor-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Numpy --&gt; Tensor</a></span></li></ul></li><li><span><a href="#Indexing,-Slicing,-Joining" data-toc-modified-id="Indexing,-Slicing,-Joining-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Indexing, Slicing, Joining</a></span></li><li><span><a href="#Joining" data-toc-modified-id="Joining-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Joining</a></span><ul class="toc-item"><li><span><a href="#Slicing" data-toc-modified-id="Slicing-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Slicing</a></span></li><li><span><a href="#squeezing" data-toc-modified-id="squeezing-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>squeezing</a></span></li></ul></li><li><span><a href="#Math-operations" data-toc-modified-id="Math-operations-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Math operations</a></span><ul class="toc-item"><li><span><a href="#torch.add()" data-toc-modified-id="torch.add()-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>torch.add()</a></span></li><li><span><a href="#torch.mul()" data-toc-modified-id="torch.mul()-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>torch.mul()</a></span></li><li><span><a href="#torch.pow" data-toc-modified-id="torch.pow-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>torch.pow</a></span></li></ul></li><li><span><a href="#log" data-toc-modified-id="log-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>log</a></span></li><li><span><a href="#Matrix-operator" data-toc-modified-id="Matrix-operator-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Matrix operator</a></span></li><li><span><a href="#Tensor-on-CPU-&amp;-GPU" data-toc-modified-id="Tensor-on-CPU-&amp;-GPU-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Tensor on CPU &amp; GPU</a></span></li></ul></div>

## Create Tensor
### Zeros, ones, arrange

In [ ]:
# max and min and mean and std ㅅ

In [1]:
import torch

In [3]:
# Make 2-by-3 tensor
X = torch.zeros(2,3)
X

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
X1 = torch.ones(2,3)
X1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

## TORCH.TENSOR
> A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type.
> Torch defines nine `CPU tensor` types and nine `GPU tensor` types:

<table class="docutils align-default">
<colgroup>
<col style="width: 19%">
<col style="width: 34%">
<col style="width: 21%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Data type</p></th>
<th class="head"><p>dtype</p></th>
<th class="head"><p>CPU tensor</p></th>
<th class="head"><p>GPU tensor</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>32-bit floating point</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.float32</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.float</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.FloatTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.FloatTensor</span></code></p></td>
</tr>
<tr class="row-odd"><td><p>64-bit floating point</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.float64</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.double</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.DoubleTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.DoubleTensor</span></code></p></td>
</tr>
<tr class="row-even"><td><p>16-bit floating point</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.float16</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.half</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.HalfTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.HalfTensor</span></code></p></td>
</tr>
<tr class="row-odd"><td><p>8-bit integer (unsigned)</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.uint8</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.ByteTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.ByteTensor</span></code></p></td>
</tr>
<tr class="row-even"><td><p>8-bit integer (signed)</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.int8</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.CharTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.CharTensor</span></code></p></td>
</tr>
<tr class="row-odd"><td><p>16-bit integer (signed)</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.int16</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.short</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.ShortTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.ShortTensor</span></code></p></td>
</tr>
<tr class="row-even"><td><p>32-bit integer (signed)</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.int32</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.int</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.IntTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.IntTensor</span></code></p></td>
</tr>
<tr class="row-odd"><td><p>64-bit integer (signed)</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.int64</span></code> or <code class="docutils literal notranslate"><span class="pre">torch.long</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.LongTensor</span></code></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.LongTensor</span></code></p></td>
</tr>
<tr class="row-even"><td><p>Boolean</p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">torch.bool</span></code></p></td>
<td><p><a class="reference internal has-code" href="#torch.BoolTensor" title="torch.BoolTensor"><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.BoolTensor</span></code></a></p></td>
<td><p><code class="xref py py-class docutils literal notranslate"><span class="pre">torch.cuda.BoolTensor</span></code></p></td>
</tr>
</tbody>
</table>

In [10]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x.type())
print(x)

torch.FloatTensor
tensor([[0.0000e+00, 0.0000e+00, 1.0570e+21],
        [1.6969e-07, 1.0533e+21, 5.3642e-08]])


In [11]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
print(x.type())
print(x)

torch.IntTensor
tensor([[          0,           0, -2147483648],
        [          0, -2147483648,           0]], dtype=torch.int32)


## Numpy to Tensor & Tensor toNumpy 

### Numpy --> Tensor

In [16]:
x = torch.FloatTensor(2,3)
x

tensor([[1.3371e+22, 4.1959e-08, 2.6851e-06],
        [1.6785e-07, 1.0442e-08, 1.0548e-08]])

In [1]:
import numpy as np 
# define numpy 
x1 = np.random.rand(2,3,).astype(int)
x1

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
# convert to tensor
x2 = torch.from_numpy(x1)
print(x2.type())
print(x2)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [7]:
# torch.tensor--> numpy 
x2.numpy()

array([[0, 0, 0],
       [0, 0, 0]])

## Indexing, Slicing, Joining

In [6]:
# indexing 
# torch.index_select(input, dim, index)
x = torch.rand(4,3)
indices = torch.tensor([0, 2])
# row 
torch.index_select(x, 0, indices)
# columns
torch.index_select(x, 1, indices)

tensor([[0.2756, 0.2484],
        [0.6346, 0.9609],
        [0.8173, 0.1188],
        [0.8398, 0.5247]])

In [ ]:
# pythonic indexing

x[:,0]
x[0,:]
x[0:2,0:2]

In [ ]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

## Joining

In [7]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [12]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### Slicing


chunk or split

In [14]:
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

In [13]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x_1, x_2 = torch.chunk(z1,2,dim=0)
x_1, x_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [15]:

x_1, x_2 = torch.split(z1,2,dim=0)
x_1, x_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [ ]:
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

z1,x_1,x_2,z1,y_1,y_2,y_3

In [ ]:
# torch.split(tensor,split_size,dim=0) -> split into specific size

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

z1,x1,x2,y1

### squeezing

In [ ]:
# torch.squeeze(input,dim=None) -> reduce dim by 1

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()

In [ ]:
# torch.unsqueeze(input,dim=None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

## Math operations

pointwise

### torch.add()

In [11]:
# torch.add()
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [12]:
# torch.add() pointwise addtion
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

x1,x2,x1+10,x2-10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

### torch.mul()

In [ ]:
# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3

In [ ]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

### torch.pow


In [ ]:
# torch.pow(base,exponent)
x1 = torch.FloatTensor(3,4)
torch.pow(x1,2),x1**2

In [13]:
# torch.exp(tensor,out=None) 

x1 = torch.FloatTensor(3,4)
print(x1)
torch.exp(x1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## log


In [ ]:
# torch.log(input, out=None) -> natural logarithm

x1 = torch.FloatTensor(3,4)
torch.log(x1)

## Matrix operator

In [ ]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

In [ ]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(3,4)

torch.dot(x1,x2)

In [ ]:
# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)

x1,x1.t()

In [ ]:
# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)

x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

TORCH.BMM
torch.bmm(input, mat2, deterministic=False, out=None) → Tensor
Performs a batch matrix-matrix product of matrices stored in input and mat2.

input and mat2 must be 3-D tensors each containing the same number of matrices.

If input is a (b \times n \times m)(b×n×m) tensor, mat2 is a (b \times m \times p)(b×m×p) tensor, out will be a (b \times n \times p)(b×n×p) tensor.

\text{out}_i = \text{input}_i \mathbin{@} \text{mat2}_i

This function does not broadcast. For broadcasting matrix products, see torch.matmul().

In [ ]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

In [ ]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)

x1,torch.eig(x1,True)

## Tensor on CPU & GPU

In [8]:
# cpu tensor
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
# cpu to gpu 
x_gpu = x.cuda()
x_gpu

AssertionError: 
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

In [ ]:
# cpu to gpu 
x_cpu = x_gpu.cpu()